# -*- coding: utf-8 -*-
"""TASK1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/abhi1328oss/28ac869f088b91dba9b3d632e3ab8b7b/untitled2.ipynb
"""

!pip install pandas numpy matplotlib scikit-learn statsmodels

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv('DATASET.csv', encoding='latin1')

df.head()

df['Order Date'] = pd.to_datetime(df['Order Date'])
df.set_index('Order Date', inplace=True)
df = df.sort_index()

# Fill missing values
df = df.fillna(method='ffill')

df.info()

df['day'] = df.index.day
df['month'] = df.index.month
df['year'] = df.index.year
df['day_of_week'] = df.index.dayofweek

import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))
plt.plot(df['Sales'])
plt.title("Sales Over Time")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X = df[['day', 'month', 'year', 'day_of_week']]
y = df['Sales']

X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=False)

model = LinearRegression()
model.fit(X_train, y_train)

predictions = model.predict(X_test)

from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mae = mean_absolute_error(y_test, predictions)
rmse = np.sqrt(mean_squared_error(y_test, predictions))

print("MAE:", mae)
print("RMSE:", rmse)

plt.figure(figsize=(10,5))

plt.plot(y_test.index, y_test, label='Actual')
plt.plot(y_test.index, predictions, label='Predicted')

plt.legend()
plt.title("Actual vs Predicted Sales")
plt.show()

from statsmodels.tsa.arima.model import ARIMA

model = ARIMA(df['Sales'], order=(5,1,0))
model_fit = model.fit()

forecast = model_fit.forecast(steps=30)

print(forecast)

plt.figure(figsize=(10,5))

plt.plot(df.index, df['Sales'], label='Past Sales')
plt.plot(pd.date_range(df.index[-1], periods=30), forecast, label='Forecast')

plt.legend()
plt.title("30-Day Sales Forecast")
plt.show()

